a = input('Digite algo: ')
print('O tipo primitivo do que foi digitado é: ', type(a))
print('Só tem espaços: ', a.isspace())
print('Só tem números: ', a.isnumeric())
print('É alfabetico: ', a.isalpha())
print('É alfanumerico: ', a.isalnum())
print('Está em maiuscula: ', a.isupper())
print('Esta em minusculo: ', a.islower())
print('Esta capitalizada: ', a.istitle())
